# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TapAdditionsKitV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapAdditionsKitV2
  pod 'TapSwiftFixesV2'

end